language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
script:
- python setup.py test
deploy:
  provider: pypi
  user: wixmcloud
  skip_existing: true
  password:
    secure: jU9uBt0XV7q9raxf9w5/zaoEPfNFGQim3RogDvwNL92WVh7gWbRLRhc7BRv28Yrvx/iy5KgnGlHbNMLR9ChTh3+d6yfTSHlbJfBikyQioFWAlq3dbs0JT/MowBVogr30pfpJG/ZaJ/MB4434PguQaf0CHEw7ByQHrrgss0JkCtkJ+lIDM9vb/79eJQ8O70CKj6jN25uD7wLPeTG9BQMHtLJk3/D31jzdMgHz0tScyzfuuovU2p6Zp4uJ8YwUhnUHtH9yUfDDfNBouCVMgG25W+glGbift0UX/iLs3rZ2UtayQ9MkH4sx3+Aa3YghVNjd4awqLBrWjr5cbUvEJBhLG2GLyrRnsltgoSsvRQDh44FIch88Fmarh3rlldM1isPZPL5Kiw/BFdyfril0nikaZuHg8kRIiyObn+8Q7RfGg3KXtS1GX0Giel+y9SWfE7i8wvbkiFqi5Apxr3WMCa0sHJC4RzccvprxKr20Wu8dIrIqlGOb18wINouwM47P27i4PT9oj4FewfFIEYXzgqFVXdmspEvQG0j8OgPZ7G45JQDnSWYKnhAvEnYEP29c/tvIPwa8VFDhTS7nJvNjJMDsHLxX4oJZwiimVN/zoW9DweR/j+tkNnVik5OQhziKa0T6mbUi8QOPpg1b54C5H797mIQm2Xl/zRsuSFTIrz+2TB8=
  on:
    branch: master