language: python
python:
- '2.7'
- '3.6'
install:
- pip install .
script:
- python setup.py test
deploy:
  provider: pypi
  user: wixmcloud
  password:
    secure: ACuBXnEuoT5bilh6jg7qTmDHaccAJli1medKPg23p77qMwdJETbLjoRrh8rnoRX+Uk74qGzJ8JEdmy22ZuGe6VJ+ZMuCprQG84/JJE+/IttqgCGjIk6vMc9BnBxcUlPBKWOzkrnBhWhmz++q+clPTAmCf8qmmZtLcsbb00P3W0/oeBWUzfptfu+CZAzupVt1R7Jvwg6klcec/hDqAGhbU8NjN3VzLs4A2dnhfRnEOPZ7HucG7ZWlWSt9ZaN3Bv842RqmP+2y6Qpto0r+mMxja/xaeQAn5sd9XaqjVMpJN5DwLTj6wnN+Jy8HbrNAG78SidqXxXjGfYGr2qSYMH1giv7R3tbihlDS8OKIUIyGMRFN9/TaE/ONR+KwwXJLtXAsdO2qJ3eZB/sOdZgFOjfHxqE10MFAIFFYOQdMsVX2b6TnOIq8K1mA5P2u3r6Yq5RtXsqihexdX3r4Ehps9Bq2nAh7YRUt4hktZny4sBQ1H3daGxoJn/L0Gs4eiZjaebMPxil6z0fkkXab692EkE7GW7FoaWz/lAzokJX6/EB7RN55oi7BYKWc72PgPYxmcy2L2h1iqeCvvx6gL9pkI7E6l5kRxvZJ6TKNNaXK2cfGa3q6JAZdLHun2tQDxm7DPw6GFnsJDqsDTNAJhz0BE9cDscrAwRhT4Qa73XN3pvGVbxo=
  on:
    branch: master